# Main configuration file

# Global settings
settings:
  target_generator_handler: ratatosk.ext.scilife.sample.target_generator

ratatosk.lib.tools.samtools:
  SamToBam:
    parent_task: ratatosk.lib.align.bwa.Sampe

ratatosk.lib.tools.picard:
  DuplicationMetrics:
    parent_task: ratatosk.lib.tools.picard.MergeSamFiles
  AlignmentMetrics:
    parent_task: ratatosk.lib.tools.picard.DuplicationMetrics
  InsertMetrics:
    parent_task: ratatosk.lib.tools.picard.DuplicationMetrics
  HsMetrics:
    parent_task: ratatosk.lib.tools.picard.DuplicationMetrics
  SortSam:
    parent_task: ratatosk.lib.tools.samtools.SamToBam
  MergeSamFiles:
    parent_task: ratatosk.lib.tools.picard.SortSam

ratatosk.lib.tools.gatk:
  RealignerTargetCreator:
    parent_task: ratatosk.lib.tools.picard.MergeSamFiles
  IndelRealigner:
    parent_task:
    - ratatosk.lib.tools.picard.MergeSamFiles
    - ratatosk.lib.tools.gatk.RealignerTargetCreator
    - ratatosk.lib.tools.gatk.UnifiedGenotyper
  BaseRecalibrator:
    parent_task: ratatosk.lib.tools.gatk.IndelRealigner
  PrintReads:
    parent_task:
      - ratatosk.lib.tools.gatk.InputBamFile
      - ratatosk.lib.tools.gatk.BaseRecalibrator
  ClipReads:
    parent_task: ratatosk.lib.tools.gatk.PrintReads
  UnifiedGenotyper:
    parent_task: ratatosk.lib.tools.gatk.ClipReads
  VariantFiltration:
    parent_task: ratatosk.lib.tools.gatk.UnifiedGenotyper
  VariantEval:
    parent_task: ratatosk.lib.tools.gatk.VariantFiltration
  ReadBackedPhasing:
    diff_label:
      - -variants-combined
      - 
    parent_task:
      - ratatosk.lib.tools.picard.MergeSamFiles
      - ratatosk.lib.tools.gatk.UnifiedGenotyper
