picard:
  InputBamFile:
    parent_task: ratatosk.lib.tools.samtools.SamToBam
  SortSam:
    parent_task: ratatosk.lib.tools.samtools.SamToBam
  MergeSamFiles:
    parent_task: ratatosk.lib.tools.picard.SortSam
  DuplicationMetrics:
    parent_task: ratatosk.lib.tools.picard.MergeSamFiles
  AlignmentMetrics:
    parent_task: ratatosk.lib.tools.picard.DuplicationMetrics
  InsertMetrics:
    parent_task: ratatosk.lib.tools.picard.DuplicationMetrics
  HsMetrics:
    parent_task: ratatosk.lib.tools.picard.DuplicationMetrics

samtools:
  SamToBam:
    parent_task: ratatosk.lib.align.bwa.Sampe

fastqc:
  parent_task: ratatosk.lib.align.bwa.InputFastqFile
